version: "3"

services:
  janus-gateway:
    image: pimenas/docker-janus:latest
    container_name: janus-gateway
    volumes:
      - ./etc/janus/:/opt/janus/etc/janus/
    ports:
      - 8088:8088
      - 8188:8188
    network_mode: "host"
