version: "2"

services:
  janus-gateway:
    image: pimenas/docker-janus:latest
    container_name: janus-gateway
    volumes:
      - ./janus/etc/janus/:/opt/janus/etc/janus/
      - ./janus/janus.log:/var/log/janus.log
    ports:
      - 8088:8088
      - 8188:8188
    network_mode: "host"
    restart: always
